apiVersion: v1
kind: PersistentVolume
metadata:
  name: op-assets-pv
spec:
  capacity:
    storage: 2Gi
  accessModes: ["ReadWriteOnce"]
  storageClassName: manual 
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /host/dir/path